import type { MockRule } from '../types';

export function convertRuleToPostman(rule: MockRule): string {
  const bodyContent = typeof rule.response === 'string'
    ? rule.response
    : JSON.stringify(rule.response, null, 2);

  const postmanItem = {
    name: rule.url,
    request: {
      method: rule.method,
      header: Object.entries(rule.headers || {}).map(([key, value]) => ({
        key,
        value,
        type: 'text'
      })),
      url: {
        raw: rule.url,
        host: [rule.url],
        path: []
      },
      description: `Generated by Pocket Mocker`
    },
    response: [
      {
        name: 'Successful Response',
        originalRequest: {
          method: rule.method,
          header: [],
          url: { raw: rule.url }
        },
        status: rule.status === 200 ? 'OK' : 'Custom',
        code: rule.status,
        _postman_previewlanguage: 'json',
        header: Object.entries(rule.headers || {}).map(([key, value]) => ({
          key,
          value,
          type: 'text'
        })),
        cookie: [],
        body: bodyContent
      }
    ]
  };

  return JSON.stringify(postmanItem, null, 2);
}
